### ISSUE TITLE
fix build issue

### ISSUE THREAD

**Issue by socketbear** [socketbear/BoardGame-Helper#1]
vite-ssg 내 빌드 간 에러 발생
```
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
file:///Users/socketbear/Workspace/BoardGame-Helper/.vite-ssg-temp/main.mjs:1529
  origin: location.origin,
          ^

ReferenceError: location is not defined
    at file:///Users/socketbear/Workspace/BoardGame-Helper/.vite-ssg-temp/main.mjs:1529:11
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async build (file:///Users/socketbear/Workspace/BoardGame-Helper/node_modules/.pnpm/vite-ssg@0.20.2_k7shjfzctjeydlate74macei7a/node_modules/vite-ssg/dist/chunks/build.mjs:171:87)
    at async Object.handler (file:///Users/socketbear/Workspace/BoardGame-Helper/node_modules/.pnpm/vite-ssg@0.20.2_k7shjfzctjeydlate74macei7a/node_modules/vite-ssg/dist/node/cli.mjs:20:3)
 ELIFECYCLE  Command failed with exit code 1.
```

빌드된 `main.mjs`에서 ssg 단계에 해당 라이브러리 선언을 가져오는 것을 확인.

**Comment by socketbear** [comment]
- vite-ssg github site에 관련 버그 리포트 한 상태
- https://github.com/antfu/vite-ssg/issues/284

**Comment by socketbear** [comment]
일단 보류
